name: datalad_binder

channels:
  - default
  - conda-forge

dependencies:
  - python=3.10.*
  - pip
  - datalad=1.2.*
  - pandas
  - seaborn
  - pip:
      - nbgitpuller
      - bash_kernel
      - jupyter-notebookparams
      - jupyter-server-proxy
      - jupytext
      - jupyter_contrib_nbextensions
